### PR TITLE
change system mode to SEMI_AUTOMATIC (closes #164)

### LINKED ISSUE #164: optimize cell data usage
https://docs.particle.io/reference/firmware/electron/#optimizing-cellular-data-use-with-cloud-connectivity-on-the-electron

### PR DESCRIPTION
**Pull request by mlp6**
Based on:
https://docs.particle.io/reference/firmware/electron/#optimizing-cellular-data-use-with-cloud-connectivity-on-the-electron

Note that this requires system firmware >=0.6.0 to work!

### CODE REVIEW

**Comment by mlp6** [comment]
@Graham-H-Miller This PR will put the system into a mode that will reduce some cellular data usage, *but* it requires that the electrons be running system firmware version >=0.6.0; is that feasible?

**Comment by aforbis-stokes** [comment]
We are operating on 0.6.2 on most of our systems. Don't know if this conflicts with the Philippines systems with the SD card.

**Comment by mlp6** [comment]
This shouldn't affect anything with the SD card, so I'll merge this in for @Graham-H-Miller to test w/ the next release.

**Comment by Graham-H-Miller** [comment]
@mlp6 @aforbis-stokes  this should be fine. I can work on bringing the all the devices to 0.6.0 this week. I can get `Duke_Cal` back whenever to run the test. Just let me know which code package to utilize

**Pull request merged**
